# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-10 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='last_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
