# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-23 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='transport_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
