# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0002_auto_20161124_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='transport_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
