# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0006_add_created_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='to_addr',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
