# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0015_identitylookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='resend',
            field=models.BooleanField(default=False, help_text=b'True if this is a resend requested by the user.'),
        ),
    ]
