# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0020_outboundsendfailure_db_backed_fk_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[(b'junebug', b'Junebug'), (b'vumi', b'Vumi'), (b'http_api', b'HTTP API'), (b'wassup', b'Wassup API')], default=b'junebug', max_length=20),
        ),
    ]
